package main

const manpage = `.TH SOFTUSB-UDEV-RULES 1
.SH NAME
softusb-udev-rules \- generate udev rules for softusb USB device access
.SH SYNOPSIS
.B softusb-udev-rules
.RI [ flags ]
.SH DESCRIPTION
.B softusb-udev-rules
generates udev rules for USB device access on Linux systems.
.PP
When using the softusb Linux host HAL, applications need read/write access to
USB device nodes such as
.IR /dev/bus/usb/ ,
.IR /dev/hidraw* ,
and
.IR /dev/usb/hiddev* .
By default, these devices are only accessible to root. This tool generates udev
rules that grant access to specific users or groups, eliminating the need to run
applications as root.
.SH OPTIONS
.TP
.BI \-o " file"
Write rules to
.IR file .
When this flag is used, the generated file includes the basename of
.I file
in the comment header. The default is standard output.
.TP
.BI \-vid " id"
Filter by USB vendor ID in hexadecimal.
.TP
.BI \-pid " id"
Filter by USB product ID in hexadecimal.
.TP
.BI \-class " id"
Filter by USB interface class in hexadecimal. This matches interface class,
not device class, which correctly handles composite devices.
.TP
.BI \-user " name"
Grant access to the named user. The user must exist. Generated rules include
.BI OWNER= name .
.TP
.BI \-group " name"
Grant access to the named group. The group must exist. If omitted, the command
uses the first available group from
.BR plugdev ,
.BR input ,
and
.BR users .
.TP
.BI \-mode " mode"
Set generated device-node file permissions. The default is
.BR 0660 .
.TP
.B \-all
Generate rules for all USB devices. This is not recommended for production
systems.
.TP
.B \-hid
Generate rules for all USB HID devices.
.TP
.B \-manpage
Print this manual page to standard output and exit. This flag may also be
specified as
.BR \-\-manpage .
.PP
At least one of
.BR \-all ,
.BR \-hid ,
.BR \-vid ,
or
.B \-class
must be specified unless
.B \-manpage
is used.
.SH GENERATED FILE HEADER
Files generated with
.BI \-o " FILE"
start with this header:
.RS
.EX
### FILE-BASENAME
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

.EE
.RE
.SH EXAMPLES
.SS "Specific Device for a User"
Generate rules for a specific Logitech device and grant access to user
.B alice
and group
.BR users :
.PP
.B "Command:"
.RS
.EX
softusb-udev-rules -vid 046d -pid c52b -user alice -group users -o /etc/udev/rules.d/99-logitech.rules
.EE
.RE
.PP
.B "Generated file: /etc/udev/rules.d/99-logitech.rules"
.RS
.EX
### 99-logitech.rules
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

# Allow access to VID=046d PID=c52b (USB device)
SUBSYSTEM=="usb", ATTR{idVendor}=="046d", ATTR{idProduct}=="c52b", MODE="0660", OWNER="alice", GROUP="users"
# Allow access to VID=046d PID=c52b (hidraw)
KERNEL=="hidraw*", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c52b", MODE="0660", OWNER="alice", GROUP="users"
# Allow access to VID=046d PID=c52b (hiddev)
KERNEL=="hiddev*", SUBSYSTEM=="usbmisc", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c52b", MODE="0660", OWNER="alice", GROUP="users"
.EE
.RE
.SS "All HID Devices"
Generate rules for all USB HID devices, including keyboards, mice, and
joysticks:
.PP
.B "Command:"
.RS
.EX
softusb-udev-rules -hid -group users -o /etc/udev/rules.d/99-hid.rules
.EE
.RE
.PP
.B "Generated file: /etc/udev/rules.d/99-hid.rules"
.RS
.EX
### 99-hid.rules
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

# Allow access to all USB HIDRAW devices
KERNEL=="hidraw*", ATTRS{bInterfaceClass}=="03", MODE="0660", GROUP="users"
# Allow access to all USB HIDDEV devices
KERNEL=="hiddev*", SUBSYSTEM=="usbmisc", MODE="0660", GROUP="users"
.EE
.RE
.SS "Vendor-Specific Devices"
Generate rules for all devices from a specific vendor:
.PP
.B "Command:"
.RS
.EX
softusb-udev-rules -vid 1234 -group users -o /etc/udev/rules.d/99-vendor-1234.rules
.EE
.RE
.PP
.B "Generated file: /etc/udev/rules.d/99-vendor-1234.rules"
.RS
.EX
### 99-vendor-1234.rules
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

# Allow access to VID=1234 (USB device)
SUBSYSTEM=="usb", ATTR{idVendor}=="1234", MODE="0660", GROUP="users"
# Allow access to VID=1234 (hidraw)
KERNEL=="hidraw*", ATTRS{idVendor}=="1234", MODE="0660", GROUP="users"
# Allow access to VID=1234 (hiddev)
KERNEL=="hiddev*", SUBSYSTEM=="usbmisc", ATTRS{idVendor}=="1234", MODE="0660", GROUP="users"
.EE
.RE
.SS "All USB Devices"
Generate rules for all USB devices:
.PP
.B "Command:"
.RS
.EX
softusb-udev-rules -all -group users -o /etc/udev/rules.d/99-usb-all.rules
.EE
.RE
.PP
.B "Generated file: /etc/udev/rules.d/99-usb-all.rules"
.RS
.EX
### 99-usb-all.rules
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

# Allow access to all USB devices
SUBSYSTEM=="usb", MODE="0660", GROUP="users"
# Allow access to all USB HIDRAW devices
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="users"
# Allow access to all USB HIDDEV devices
KERNEL=="hiddev*", SUBSYSTEM=="usbmisc", MODE="0660", GROUP="users"
.EE
.RE
.PP
Granting access to all USB devices may have security implications. Use
.B \-all
only in controlled environments.
.SS "CDC Interface Class"
Generate rules for CDC devices:
.PP
.B "Command:"
.RS
.EX
softusb-udev-rules -class 02 -group users -o /etc/udev/rules.d/99-cdc.rules
.EE
.RE
.PP
.B "Generated file: /etc/udev/rules.d/99-cdc.rules"
.RS
.EX
### 99-cdc.rules
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

# Allow access to Class=02 (USB device)
SUBSYSTEM=="usb", ATTR{bInterfaceClass}=="02", MODE="0660", GROUP="users"
# Allow access to Class=02 (hidraw)
KERNEL=="hidraw*", ATTRS{bInterfaceClass}=="02", MODE="0660", GROUP="users"
# Allow access to Class=02 (hiddev)
KERNEL=="hiddev*", SUBSYSTEM=="usbmisc", ATTRS{bInterfaceClass}=="02", MODE="0660", GROUP="users"
.EE
.RE
.SH APPLYING RULES
After generating rules, reload udev and trigger a rescan:
.PP
.B "Commands:"
.RS
.EX
sudo udevadm control --reload-rules
sudo udevadm trigger
.EE
.RE
.PP
For rules to take effect on already-connected devices, you may need to unplug
and replug them.
.SH APPLYING RULES WITH SYSTEMD CREDENTIALS
systemd 256 and newer can load udev rules from system credentials named
.BR udev.rules.* .
This is useful when you want the rules managed through the systemd credential
store instead of writing directly to
.IR /etc/udev/rules.d/ .
.PP
First verify that PID 1 is systemd and the systemd version is 256 or newer:
.PP
.B "Commands:"
.RS
.EX
test "$(ps -p 1 -o comm=)" = systemd
test "$(systemctl --version | awk 'NR==1 {print $2}')" -ge 256
.EE
.RE
.PP
If either command fails, use the direct rules-file path instead:
.PP
.B "Commands:"
.RS
.EX
sudo softusb-udev-rules -hid -group users -o /etc/udev/rules.d/99-softusb.rules
sudo udevadm control --reload-rules
sudo udevadm trigger
.EE
.RE
.PP
.B "Generated file: /etc/udev/rules.d/99-softusb.rules"
.RS
.EX
### 99-softusb.rules
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

# Allow access to all USB HIDRAW devices
KERNEL=="hidraw*", ATTRS{bInterfaceClass}=="03", MODE="0660", GROUP="users"
# Allow access to all USB HIDDEV devices
KERNEL=="hiddev*", SUBSYSTEM=="usbmisc", MODE="0660", GROUP="users"
.EE
.RE
.PP
On systemd 256 or newer, generate a plaintext rules file and encrypt it into
the encrypted credential store. Encrypted credentials should be stored under
.IR /etc/credstore.encrypted/ ;
use
.IR /etc/credstore/
only for plaintext credentials.
.PP
.B "Commands:"
.RS
.EX
softusb-udev-rules -hid -group users -o ./softusb.rules
sudo install -d -m 0700 /etc/credstore.encrypted
sudo systemd-creds encrypt --name=udev.rules.softusb - /etc/credstore.encrypted/udev.rules.softusb < ./softusb.rules
rm ./softusb.rules
.EE
.RE
.PP
.B "Generated file before encryption: ./softusb.rules"
.RS
.EX
### softusb.rules
# Generated by softusb-udev-rules (https://github.com/ardnew/softusb)

# Allow access to all USB HIDRAW devices
KERNEL=="hidraw*", ATTRS{bInterfaceClass}=="03", MODE="0660", GROUP="users"
# Allow access to all USB HIDDEV devices
KERNEL=="hiddev*", SUBSYSTEM=="usbmisc", MODE="0660", GROUP="users"
.EE
.RE
.PP
Install a helper service that imports the encrypted credential, asks udev to
load credentials, reloads rules, and triggers existing devices.
.B SYSTEMD_EDITOR=tee
is used so
.B systemctl edit --full --force
writes the service unit from standard input.
.PP
.B "Command:"
.RS
.EX
sudo env SYSTEMD_EDITOR=tee systemctl edit --full --force udev-credential-sync.service <<'EOF'
[Unit]
Description=Reload softusb udev Rules from Credentials
ConditionPathExists=/etc/credstore.encrypted/udev.rules.softusb
After=systemd-udev-load-credentials.service

[Service]
Type=oneshot
ImportCredential=udev.rules.softusb
ExecStart=/usr/bin/udevadm control --load-credentials
ExecStart=/usr/bin/udevadm control --reload-rules
ExecStartPost=/usr/bin/udevadm trigger
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
.EE
.RE
.PP
Then reload systemd and enable the helper. Starting the helper runs
.BR "udevadm control --load-credentials" ,
reloads udev rules, and triggers existing devices.
.PP
.B "Commands:"
.RS
.EX
sudo systemctl daemon-reload
sudo systemctl enable --now udev-credential-sync.service
.EE
.RE
.PP
After changing the encrypted credential later, run:
.PP
.B "Command:"
.RS
.EX
sudo systemctl restart udev-credential-sync.service
.EE
.RE
.PP
The credential name
.B udev.rules.softusb
is loaded by udev as
.IR /run/udev/rules.d/softusb.rules .
.SH GROUP MEMBERSHIP
Users must be members of the specified group to access devices through group
permissions. Check which group was selected in the generated rules, then add
your user if needed:
.PP
.B "Command:"
.RS
.EX
sudo usermod -aG users "$USER"
.EE
.RE
.PP
Log out and back in for the group membership to take effect. For the current
shell only, you can reload your login session without restarting the machine:
.PP
.B "Command:"
.RS
.EX
exec sudo -iu ${USER}
.EE
.RE
.PP
.B plugdev
is common on Debian/Ubuntu systems. Arch-based and other distributions may not
create this group, so the tool falls back to
.B input
or
.B users
automatically.
.PP
If you use
.BR \-user ,
the generated rules include
.BI OWNER= name
so that user can access matching device nodes as the file owner. You can combine
.B \-user
and
.B \-group
when both owner and group access are useful.
.SH COMMON USB INTERFACE CLASSES
The
.B \-class
flag filters by USB interface class.
.TP
.B HID
.BR 03 :
Human Interface Device (keyboard, mouse, joystick).
.TP
.B Mass Storage
.BR 08 :
USB storage devices.
.TP
.B CDC
.BR 02 :
Communication Device Class (serial, modem).
.TP
.B Audio
.BR 01 :
Audio devices.
.TP
.B Video
.BR 0e :
Video devices (webcams).
.TP
.B Hub
.BR 09 :
USB hubs.
.SH TROUBLESHOOTING
.SS Permission Denied
If you still get permission errors after applying rules:
.IP 1. 3
Check group membership:
.BR "groups \"$USER\"" .
.IP 2. 3
Verify the group exists:
.BR "getent group users" .
.IP 3. 3
Verify the user exists when using
.BR \-user :
.BR "id alice" .
.IP 4. 3
Verify the rules file exists:
.BR "ls -la /etc/udev/rules.d/99-*.rules" .
.IP 5. 3
Test rule matching and look for errors:
.BR "sudo udevadm test \"$(udevadm info -q path -n /dev/hidraw0)\"" .
.IP 6. 3
Try unplugging and replugging the device.
.SS Rules Not Loading
Verify udev can parse the rules without errors:
.PP
.B "Command:"
.RS
.EX
sudo udevadm test /sys/bus/usb/devices/<device>
.EE
.RE
.PP
For systemd credentials, verify the encrypted credential exists and can be
decrypted by the local system:
.PP
.B "Commands:"
.RS
.EX
sudo test -f /etc/credstore.encrypted/udev.rules.softusb
sudo systemd-creds decrypt /etc/credstore.encrypted/udev.rules.softusb - >/dev/null
.EE
.RE
.SS Finding Device Information
Use
.B lsusb
to find VID:PID:
.PP
.B "Command:"
.RS
.EX
lsusb
# Bus 001 Device 005: ID 046d:c52b Logitech, Inc. Unifying Receiver
.EE
.RE
.PP
Use
.B udevadm
for detailed device information:
.PP
.B "Command:"
.RS
.EX
udevadm info -a -n /dev/bus/usb/001/005
.EE
.RE
.SH SEE ALSO
.BR udev (7),
.BR udevadm (8),
.BR systemd-creds (1),
.BR systemd.system-credentials (7)
`
